# fly.toml app configuration file generated for esohasl-api on 2024-08-03T22:40:43+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'aisboost-api'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']
  [http_service.concurrency]
    type = "requests"
    soft_limit = 250
    hard_limit = 750

[env]
  AUTH_DOMAIN = "aisboost.com"
  DASHBOARD_URL = "https://aisboost.com/dashboard"
  GATEWAY_URL = "https://gw.aisboost.com"
  HOME_URL = "https://aisboost.com"

[[vm]]
  size = 'shared-cpu-1x'
  memory_mb = 256